# Site settings
title: Gonzalo Borobio
#description: '"This is my site. There are many like it, but this one is mine."'
description: '"I write blog posts to exorcise my demons."'
url: 'https://gborobio73.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gonzalo Borobio'
  email: gborobio@gmail.com
  twitter_username: gborobio
  facebook_username: 
  github_username:  gborobio73
  linkedin_username:  gonzalo-borobio

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
